# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Google-PageRank
version:      0.04
version_from: lib/WWW/Google/PageRank.pm
installdirs:  site
requires:
    LWP::UserAgent:                0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
